on:
  pull_request:
    types:
      - closed

jobs:
  publish-components:
    if: github.event.pull_request.merged == true
    name: Publish Components to Pipedream Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Publish and add to registry components/*.*js (that aren't .app.js files)
        id: publish
        shell: bash {0} # don't fast fail
        run: |
          env
          cat $GITHUB_EVENT_PATH
